### ISSUE TITLE
Fails during production build

### ISSUE THREAD

**Issue by amatoro** [rdev/react-preloading-screen#1]
Failed to minify the code from this file:

 	./node_modules/react-preloading-screen/dist/index.js:1:537

**Comment by rdev** [comment]
@amatoro hi! Can you provide more details about how your project is set up?

**Comment by amatoro** [comment]
Ejected Create React App. 

React: 16.4.0
Webpack: 3.8.1
Babel-eslint: 7.2.3

Build create with node scripts/build.js

I am not sure what other information will be useful to troubleshot this, please let me know, thank you!

It seems it's trying to minify already minified code? (Just a random thought I am new with all this). 

Thank you!

**Comment by rdev** [comment]
@amatoro the issue was caused by this: https://github.com/facebook/create-react-app/issues/984#issuecomment-257105773

I just published a fix. Update to `react-preloading-screen@1.0.2` and everything should work fine :)

**Comment by amatoro** [comment]
Thank you!
