### ISSUE TITLE
IE11 Error

### ISSUE THREAD

**Issue by amatoro** [rdev/react-preloading-screen#2]
With IE11 I get an error message: "TypeError: Object doesn't support property or method 'find'" 

is IE11 supported? 

Thanks!

**Comment by amatoro** [comment]
I used the find polyfill and it's working like a charm now. 

Regards,

A.

**Comment by rdev** [comment]
Hi! Glad to year you got it resolved!
I never tested it on IE and never intended to support it, so it was bound to be broken in some way. I should have put it in the readme, sorry about that 🙈
